import type { CaseDefinition, CaseState } from "./types";

const m = (id: string, name: string, role: string, initials: string, personality: string, truth: string[], lies: string[], secrets: string[], knownFacts: string[], unknownFacts: string[], motive: string, biometrics = { stress: 28, bpm: 76, coherence: 82 }) => ({ id, name, role, initials, personality, truth, lies, secrets, knownFacts, unknownFacts, motive, biometrics });

export const CASES: CaseDefinition[] = [{
  id: "meridian-escrow", title: "El saldo fantasma", premise: "4,2 millones desaparecieron de una cuenta escrow. El auditor Martin Reyes desapareció la misma noche.", objective: "Determina quién movió el dinero y encubrió la desaparición de Reyes.", culpritId: "hale",
  clues: [
    { id: "access-log", title: "Registro de acceso", detail: "La tarjeta de Richard Hale abrió la sala de servidores a las 22:43.", suspectIds: ["hale"], discovered: false },
    { id: "compliance-email", title: "Correo de cumplimiento", detail: "Mara Lin alertó dos veces sobre una transferencia a Kestrel Holdings; Hale anuló ambas alertas.", suspectIds: ["lin", "hale"], discovered: false },
    { id: "parking-camera", title: "Cámara del garaje", detail: "Elena Voss entró al edificio de Hale a las 21:17 del 14 de julio.", suspectIds: ["voss"], discovered: false },
    { id: "badge-copy", title: "Copia de credencial", detail: "La credencial de Daniel fue clonada una semana antes; él ocultó el incidente por miedo a perder su empleo.", suspectIds: ["ortiz"], discovered: false },
    { id: "voice-note", title: "Nota de voz", detail: "Reyes dejó: «Si me ocurre algo, revisen a quien controlaba las excepciones». ", suspectIds: ["hale", "reyes"], discovered: false },
  ],
  contradictions: [
    { id: "hale-server", suspectId: "hale", claim: "Hale afirmó estar en una cena del consejo toda la noche.", evidence: "Su tarjeta abrió la sala de servidores a las 22:43.", discovered: false },
    { id: "voss-timeline", suspectId: "voss", claim: "Voss afirmó que trabajó sola en la oficina después de las 21:00.", evidence: "La cámara la sitúa en el edificio de Hale a las 21:17.", discovered: false },
  ],
  suspects: [
    m("hale", "Richard Hale", "CEO · Meridian Holdings", "RH", "Cálido y ejecutivo; contesta con párrafos amables para diluir una acusación.", ["Ordenó el desvío a Kestrel y confrontó a Reyes."], ["Dice que Reyes renunció y que estuvo en una cena."], ["Controla Kestrel Holdings y usó la sala de servidores."], ["Voss autorizó la transferencia bajo presión."], ["No sabe dónde está Reyes ahora."], "Evitar prisión y conservar el control.", { stress: 21, bpm: 69, coherence: 91 }),
    m("voss", "Elena Voss", "CFO · Meridian Holdings", "EV", "Fría, exacta y breve; se protege con vocabulario financiero.", ["Autorizó la transferencia bajo presión de Hale."], ["Niega conocer Kestrel y miente sobre su horario."], ["Fue al apartamento de Hale para exigir protección."], ["Hale presionó a Mara y Reyes encontró la discrepancia."], ["No sabe el destino final de Reyes."], "No cargar sola con un delito ajeno.", { stress: 26, bpm: 75, coherence: 86 }),
    m("lin", "Mara Lin", "Oficial de cumplimiento", "ML", "Nerviosa y cooperadora; se refugia en procesos y políticas.", ["Alertó por escrito sobre Kestrel y Hale anuló las alertas."], ["Dice que no vio a Reyes el 14 de julio."], ["Habló con Reyes por teléfono esa noche."], ["Voss fue presionada por Hale."], ["No sabe quién clonó la credencial de Daniel."], "Teme represalias de Hale.", { stress: 37, bpm: 83, coherence: 75 }),
    m("ortiz", "Daniel Ortiz", "Administrador de sistemas", "DO", "Defensivo y técnico; corrige detalles irrelevantes cuando se siente observado.", ["Su credencial fue clonada; los registros pueden ser manipulados."], ["Afirma que reportó el clon de inmediato."], ["Ocultó el clon por miedo a ser despedido."], ["Hale pidió acceso excepcional al servidor."], ["No sabe qué había en el portátil de Reyes."], "Conservar su empleo y no parecer cómplice.", { stress: 34, bpm: 79, coherence: 77 }),
    m("sato", "Naomi Sato", "Abogada externa", "NS", "Serena y calculadora; responde exactamente a lo preguntado y luego negocia.", ["Redactó un acuerdo de indemnidad para Voss que Hale nunca firmó."], ["Dice que no representaba personalmente a Hale."], ["Hale la llamó después de medianoche buscando cobertura legal."], ["Voss estaba aterrada antes de firmar."], ["No conoce la ubicación de Reyes."], "Proteger su firma y su licencia.", { stress: 18, bpm: 68, coherence: 93 }),
    m("reyes", "Tomás Reyes", "Hermano de Martin Reyes", "TR", "Irritado y directo; confunde rabia con certeza, pero no oculta el dolor.", ["Martin le envió una nota de voz sobre excepciones."], ["Afirma que Hale amenazó a Martin en persona."], ["Exagera lo que sabe de esa amenaza."], ["Martin desconfiaba del círculo ejecutivo."], ["No sabe si Martin sigue vivo."], "Encontrar a su hermano, aunque culpe al primero que encaje.", { stress: 52, bpm: 89, coherence: 63 }),
  ],
}, {
  id: "gallery-blackout", title: "La pieza ausente", premise: "Durante un apagón de 11 minutos desapareció una escultura asegurada. El informe eléctrico fue alterado.", objective: "Identifica a quien organizó el robo antes de que la obra salga de la ciudad.", culpritId: "ibarra",
  clues: [{ id: "freight", title: "Manifiesto de carga", detail: "Un furgón autorizado por Lucía Ibarra salió vacío en papel, pero con 46 kg adicionales.", suspectIds: ["ibarra"], discovered: false }, { id: "relay", title: "Relé anulado", detail: "El apagón fue programado desde la consola de seguridad, no por una falla de red.", suspectIds: ["ibarra", "vega"], discovered: false }],
  contradictions: [{ id: "ibarra-freight", suspectId: "ibarra", claim: "Ibarra afirmó que el furgón no llegó esa noche.", evidence: "El manifiesto y la báscula registran su salida.", discovered: false }],
  suspects: [m("ibarra", "Lucía Ibarra", "Directora de operaciones", "LI", "Controlada y persuasiva; convierte cada pregunta en una cuestión logística.", ["Organizó el apagón y sacó la obra en un furgón."], ["Niega que el furgón llegara."], ["Tiene deudas de juego."], ["Vega podía programar la consola."], ["No sabe quién vio la carga."], "Pagar una deuda antes de que la alcancen."), m("vega", "Bruno Vega", "Jefe de seguridad", "BV", "Seco, reglamentario, obsesivo con el protocolo.", ["Su consola fue usada durante el apagón."], ["Dice que su terminal nunca quedó desatendida."], ["Se ausentó siete minutos para atender una llamada."], ["Ibarra pidió los planos de carga."], ["No sabe dónde terminó la obra."], "Evitar que su negligencia lo destruya."), m("mora", "Adriana Mora", "Curadora", "AM", "Elocuente y teatral; ama los detalles de arte, evita los números.", ["La obra tenía una grieta que reducía su valor."], ["Dice que nunca habló de la grieta."], ["Quería ocultar que aprobó una restauración fallida."], ["Ibarra insistía en asegurar la pieza."], ["No sabe de los furgones."], "Salvar su reputación profesional."), m("rios", "Mateo Ríos", "Técnico eléctrico", "MR", "Cansado, irónico y preciso cuando habla de sistemas.", ["El relé fue anulado desde seguridad."], ["Niega haber entregado credenciales."], ["Prestó su tarjeta temporal a Vega semanas antes."], ["La falla no fue eléctrica."], ["No sabe quién dio la orden."], "No perder su contrato."), m("soler", "Clara Soler", "Coleccionista", "CS", "Elegante y provocadora; disfruta parecer más sospechosa de lo que es.", ["Ofreció comprar la obra antes del apagón."], ["Niega haber subido su oferta."], ["Sabía que la pieza tenía una grieta."], ["Ibarra la llamó dos días antes."], ["No sabe quién la robó."], "Adquirir la obra con ventaja, legal o no."), m("naranjo", "Iván Naranjo", "Transportista", "IN", "Práctico y ansioso; contesta con tiempos, rutas y recibos.", ["Su furgón salió con más peso."], ["Dice que firmó un manifiesto vacío."], ["Le pagaron una ruta extra en efectivo."], ["Ibarra autorizó la salida."], ["No sabía qué llevaba."], "No quedar implicado en un delito mayor.")],
}];

export function createCaseState(id: string): CaseState {
  const definition = CASES.find((item) => item.id === id) ?? CASES[0];
  return { ...structuredClone(definition), suspects: definition.suspects.map((suspect) => ({ ...structuredClone(suspect), history: [], revealedClueIds: [], pressure: 0 })), history: [], eventLog: [], phase: "briefing", timerEndsAt: Date.now() + 25 * 60_000, revision: 1 };
}
