"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { CaseState, SuspectState } from "@/lib/game/types";
import { CASES } from "@/lib/game/cases";

type Panel = "evidence" | "contradictions" | "case" | "guide";
const formatTime = (end: number) => { const seconds = Math.max(0, Math.floor((end - Date.now()) / 1000)); return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; };

export function DashboardShell() {
  const [state, setState] = useState<CaseState | null>(null); const [selectedId, setSelectedId] = useState("hale"); const [draft, setDraft] = useState(""); const [panel, setPanel] = useState<Panel>("evidence"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [now, setNow] = useState(Date.now());
  const selected = state?.suspects.find((item) => item.id === selectedId) ?? state?.suspects[0];
  const load = useCallback(async (caseId = "meridian-escrow") => { const response = await fetch(`/api/game?caseId=${encodeURIComponent(caseId)}`, { cache: "no-store" }); if (!response.ok) throw new Error("No se pudo cargar el expediente."); const next = await response.json() as CaseState; setState(next); setSelectedId(next.suspects[0].id); }, []);
  useEffect(() => { const bootstrap = window.setTimeout(() => { void load().catch((reason) => setError(reason.message)); }, 0); const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => { window.clearTimeout(bootstrap); window.clearInterval(timer); }; }, [load]);
  const act = async (action: "start" | "interrogate" | "accuse", extra: Record<string, string> = {}) => { setBusy(true); setError(""); try { const response = await fetch("/api/game", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, caseId: state?.id ?? "meridian-escrow", ...extra }) }); const payload = await response.json() as CaseState | { error: string }; if (!response.ok || "error" in payload) throw new Error("error" in payload ? payload.error : "La operación no pudo completarse."); setState(payload); } catch (reason) { setError(reason instanceof Error ? reason.message : "Error de conexión. Intenta de nuevo."); } finally { setBusy(false); } };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!draft.trim() || !selected) return; const question = draft.trim(); setDraft(""); void act("interrogate", { suspectId: selected.id, question }); };
  const visibleMessages = useMemo(() => state?.history.filter((item) => item.suspectId === selected?.id) ?? [], [state, selected]);
  if (!state) return <main className="min-h-screen grid place-items-center bg-[#101315] text-stone-200">Cargando expediente…</main>;
  const discovered = state.clues.filter((item) => item.discovered); const contradictions = state.contradictions.filter((item) => item.discovered);
  return <main className="min-h-screen bg-[#101315] text-stone-100 p-3 sm:p-5"><div className="mx-auto max-w-7xl space-y-3">
    <header className="rounded-xl border border-stone-700 bg-[#171b1d] px-4 py-3 flex flex-wrap gap-4 items-center justify-between shadow-sm"><div><p className="text-xs uppercase tracking-[.18em] text-amber-400">Expediente activo · {state.id}</p><h1 className="text-lg sm:text-xl font-semibold">{state.title}</h1></div><div className="flex flex-wrap items-end gap-4 text-sm"><label className="grid gap-1 text-[10px] uppercase tracking-wider text-stone-500">Caso<select value={state.id} onChange={(event) => { void load(event.target.value).catch((reason) => setError(reason.message)); }} className="rounded border border-stone-600 bg-[#101315] px-2 py-1.5 text-sm normal-case tracking-normal text-stone-100"><option value="meridian-escrow">El saldo fantasma</option><option value="gallery-blackout">La pieza ausente</option></select></label><Status label="Tiempo" value={formatTime(state.timerEndsAt)} /><Status label="Pistas" value={`${discovered.length}/${state.clues.length}`} /><Status label="Estado" value={state.phase === "briefing" ? "Briefing" : state.phase === "resolved" ? "Cerrado" : "Investigando"} /></div></header>
    {state.phase === "briefing" ? <Briefing state={state} onStart={() => void act("start")} busy={busy} /> : state.phase === "resolved" ? <Result state={state} onRestart={() => void act("start")} /> : <>
      <section className="grid gap-3 lg:grid-cols-[245px_minmax(0,1fr)]"><aside className="rounded-xl border border-stone-700 bg-[#171b1d] p-2"><p className="px-2 py-2 text-xs font-semibold uppercase tracking-wider text-stone-400">Sospechosos</p>{state.suspects.map((suspect) => <button key={suspect.id} onClick={() => setSelectedId(suspect.id)} className={`w-full rounded-lg px-3 py-3 text-left flex gap-3 transition ${selected?.id === suspect.id ? "bg-amber-400 text-stone-950" : "hover:bg-stone-800"}`}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-current text-xs font-bold">{suspect.initials}</span><span className="min-w-0"><b className="block text-sm">{suspect.name}</b><small className="block truncate opacity-75">{suspect.role}</small></span></button>)}</aside>
        <section className="min-h-[580px] rounded-xl border border-stone-700 bg-[#171b1d] flex flex-col overflow-hidden"><div className="border-b border-stone-700 p-4 flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-amber-400">Sala de interrogatorio</p><h2 className="text-xl font-semibold">{selected?.name}</h2><p className="text-sm text-stone-400">{selected?.role}</p></div>{selected && <Telemetry suspect={selected} />}</div><div className="flex-1 space-y-4 overflow-y-auto p-4" aria-live="polite">{visibleMessages.length ? visibleMessages.map((item) => <article key={item.id} className={`max-w-[85%] rounded-xl px-4 py-3 text-sm leading-6 ${item.role === "detective" ? "ml-auto bg-amber-400 text-stone-950" : "border border-stone-700 bg-[#111415]"}`}><p className="mb-1 text-[10px] font-bold uppercase tracking-wider opacity-60">{item.role === "detective" ? "Detective" : selected?.name}</p>{item.text}</article>) : <div className="grid h-full place-items-center text-center text-stone-400"><div><p className="text-lg text-stone-200">La sala está en silencio.</p><p className="mt-1 text-sm">Haz una pregunta concreta. Compara respuestas y guarda lo verificable.</p></div></div>}</div>{error && <p role="alert" className="mx-4 mb-2 rounded-lg border border-red-800 bg-red-950/40 p-3 text-sm text-red-200">{error}</p>}<form onSubmit={submit} className="border-t border-stone-700 p-3 flex gap-2"><label className="sr-only" htmlFor="question">Pregunta para {selected?.name}</label><input id="question" value={draft} maxLength={480} onChange={(event) => setDraft(event.target.value)} disabled={busy} placeholder={busy ? "Esperando respuesta…" : "Pregunta por una coartada, una relación o una prueba…"} className="min-w-0 flex-1 rounded-lg border border-stone-600 bg-[#101315] px-4 py-3 text-base outline-none focus:border-amber-400 disabled:opacity-50"/><button disabled={busy || !draft.trim()} className="rounded-lg bg-amber-400 px-5 py-3 text-sm font-bold text-stone-950 hover:bg-amber-300 disabled:opacity-50">{busy ? "Interrogando…" : "Interrogar"}</button></form></section></section>
      <section className="rounded-xl border border-stone-700 bg-[#171b1d]"><nav className="flex overflow-x-auto border-b border-stone-700" aria-label="Herramientas del caso">{(["evidence", "contradictions", "case", "guide"] as Panel[]).map((name) => <button key={name} onClick={() => setPanel(name)} className={`shrink-0 px-4 py-3 text-sm font-medium capitalize ${panel === name ? "border-b-2 border-amber-400 text-amber-300" : "text-stone-400 hover:text-stone-100"}`}>{name === "evidence" ? "Pistas" : name === "contradictions" ? "Contradicciones" : name === "case" ? "Caso" : "Cómo jugar"}</button>)}</nav><div className="p-4"><InvestigationPanel panel={panel} state={state} discovered={discovered} contradictions={contradictions} /></div></section>
      <section className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-red-950 bg-red-950/20 p-4"><div><h2 className="font-semibold">Formula una teoría</h2><p className="text-sm text-stone-400">La acusación cierra el caso. Las biométricas son ambiguas: no prueban una mentira.</p></div><select aria-label="Sospechoso a acusar" defaultValue="" onChange={(event) => { if (event.target.value && window.confirm("¿Cerrar el caso con esta acusación?")) void act("accuse", { suspectId: event.target.value }); event.currentTarget.value = ""; }} className="rounded-lg border border-red-800 bg-[#101315] px-3 py-2 text-sm"><option value="" disabled>Acusar a…</option>{state.suspects.map((suspect) => <option key={suspect.id} value={suspect.id}>{suspect.name}</option>)}</select></section>
    </>}</div></main>;
}
function Status({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] uppercase tracking-wider text-stone-500">{label}</p><p className="font-mono text-sm text-amber-300">{value}</p></div>; }
function Telemetry({ suspect }: { suspect: SuspectState }) { const b = suspect.biometrics; return <div className="grid grid-cols-3 gap-3 text-center text-xs"><Meter label="Estrés" value={`${b.stress}%`} /><Meter label="Pulso" value={`${b.bpm}`} /><Meter label="Coherencia" value={`${b.coherence}%`} /><p className="col-span-3 text-[11px] text-stone-500">Lectura ambigua · {b.lastTopic ?? "sin muestras"}</p></div>; }
function Meter({ label, value }: { label: string; value: string }) { return <div><p className="text-stone-500">{label}</p><b className="text-base text-stone-100">{value}</b></div>; }
function Briefing({ state, onStart, busy }: { state: CaseState; onStart: () => void; busy: boolean }) { return <section className="mx-auto mt-12 max-w-2xl rounded-xl border border-stone-700 bg-[#171b1d] p-6 sm:p-9"><p className="text-xs uppercase tracking-[.18em] text-amber-400">Briefing</p><h2 className="mt-2 text-3xl font-semibold">{state.title}</h2><p className="mt-4 text-lg leading-8 text-stone-300">{state.premise}</p><p className="mt-5 rounded-lg border border-stone-700 bg-[#101315] p-4 text-sm">Objetivo: {state.objective}</p><button onClick={onStart} disabled={busy} className="mt-6 rounded-lg bg-amber-400 px-5 py-3 font-bold text-stone-950 disabled:opacity-60">{busy ? "Preparando…" : "Iniciar investigación"}</button></section>; }
function InvestigationPanel({ panel, state, discovered, contradictions }: { panel: Panel; state: CaseState; discovered: CaseState["clues"]; contradictions: CaseState["contradictions"] }) { if (panel === "evidence") return <List title="Pistas aseguradas" empty="Aún no hay pistas. Pregunta por hechos concretos y coartadas." items={discovered.map((item) => `${item.title} — ${item.detail}`)} />; if (panel === "contradictions") return <List title="Contradicciones verificadas" empty="Ninguna todavía. Una contradicción conecta una afirmación con una prueba." items={contradictions.map((item) => `${item.claim} ${item.evidence}`)} />; if (panel === "case") return <div><h3 className="font-semibold">Objetivo del caso</h3><p className="mt-2 text-sm text-stone-300">{state.objective}</p><p className="mt-4 text-sm text-stone-400">Compara los relatos entre salas: cada sospechoso conserva una conversación independiente.</p></div>; return <div className="grid gap-3 text-sm sm:grid-cols-2"><p><b>1. Interroga.</b><br className="sm:hidden"/> Haz preguntas precisas.</p><p><b>2. Observa.</b><br className="sm:hidden"/> El estrés orienta, no demuestra.</p><p><b>3. Conecta.</b><br className="sm:hidden"/> Guarda pistas y contradicciones.</p><p><b>4. Acusa.</b><br className="sm:hidden"/> Cierra cuando tengas una teoría.</p></div>; }
function List({ title, empty, items }: { title: string; empty: string; items: string[] }) { return <div><h3 className="font-semibold">{title}</h3>{items.length ? <ul className="mt-3 space-y-2">{items.map((item) => <li key={item} className="rounded-lg border border-stone-700 bg-[#101315] p-3 text-sm text-stone-300">{item}</li>)}</ul> : <p className="mt-2 text-sm text-stone-400">{empty}</p>}</div>; }
function Result({ state, onRestart }: { state: CaseState; onRestart: () => void }) { const culprit = state.suspects.find((suspect) => suspect.id === state.culpritId); const accused = state.suspects.find((suspect) => suspect.id === state.accusation?.suspectId); const won = state.accusation?.correct; return <section className="mx-auto mt-12 max-w-2xl rounded-xl border border-stone-700 bg-[#171b1d] p-6 sm:p-9"><p className={`text-xs font-bold uppercase tracking-[.18em] ${won ? "text-emerald-300" : "text-red-300"}`}>{won ? "Caso resuelto" : "Acusación incorrecta"}</p><h2 className="mt-2 text-3xl font-semibold">{won ? "Tu teoría era correcta." : "La investigación tomó un giro equivocado."}</h2><p className="mt-4 text-stone-300">Acusaste a <b>{accused?.name}</b>. La responsable era <b>{culprit?.name}</b>.</p><p className="mt-4 rounded-lg border border-stone-700 bg-[#101315] p-4 text-sm text-stone-300">{culprit?.truth[0]} {culprit?.secrets[0]}</p><button onClick={onRestart} className="mt-6 rounded-lg bg-amber-400 px-5 py-3 font-bold text-stone-950">Reabrir caso</button></section>; }
